### ISSUE TITLE
tokenize() is not compatible with expand_macros()

### ISSUE THREAD

**Issue by ShaheedHaque** [ned14/pcpp#1]
I'm not sure if this is regarded as a bug, but the output form tokenize() is not consumable by expand_macros() because the ".source" attribute is missing. I can workaround it like this:

        preproc = pcpp.preprocessor.Preprocessor
        tokens = preproc.tokenize("text")
        for t in tokens:
            t.source = "some random value"
        tokens = preproc.expand_macros(tokens)

If the idea is to keep tokens lightweight, perhaps tokenize() could take an optional "source" parameter which, only if not None would be added to the token?

**Comment by ShaheedHaque** [comment]
Thanks for the kind reply. I'm afraid that I no longer have a usable context in which to try things and provide a useful reply.

**Comment by ned14** [comment]
Sorry for such a late reply. To be honest, I forgot about this issue. My apologies.
