### ISSUE TITLE
#line directive not output for first include

### ISSUE THREAD

**Issue by Sei-Lisa** [ned14/pcpp#17]
Say this is test.c (I fed it into stdin, so the actual name should not matter; the bug can be reproduced either way anyway):

```c
#include "inc.h"
test1
#include "inc.h"
test2
```
and this is inc.h:
```c
inc1
#ifndef __inc_h__
inc2
#define __inc_h__
inc3
#endif //__inc_h__
inc4
```

The output from the above is:

```c
inc1

inc2

inc3

inc4
#line 2 "<stdin>"
test1
#line 1 "inc1.h"
inc1





inc4
#line 4 "<stdin>"
test2
```
Note the absence of any indication that the first appearances of inc1, inc2, inc3 and inc4 come from inc.h.

**Comment by ned14** [comment]
Thanks for the report. I am currently on vacation in the United States. Due to lack of computing devices, I cannot verify nor fix this BR, but I shall do so when I return to Europe in about ten days time.

**Comment by ned14** [comment]
Fixed. Thanks for the bug report!
