### ISSUE TITLE
how to make pcpp ignore # followed by whitespace?

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [ned14/pcpp#27]
I'd like to modify pcpp to make it ignore # followed by whitespace, e.g., so that pcpp will ignore something like `# if` or `# error`.  I believe that this will require overriding `parsegen`, but that function is rather sparsely documented and I'm having difficulty reverse engineering it.  I suspect that I need to modify the code immediately following the comment "# Skip over whitespace".  Any suggestions re. how to make this change will be appreciated.

**Comment by Phillip-M-Feldman** [comment]
I implemented a solution in my local copy of the code.  The change involves a small number of lines beginning at line 1120 in preprocessor.py.  The updated code follows:

if tok.value == '#':

                try:

                    # The following two lines prevent a pound sign immediately followed by
                    # white space from being treated as a preprocessor directive:
                    if i == 0 and len(x) >= 2 and x[1].type == 'CPP_WS':
                       raise OutputDirective()

                    # If we got here, the pound sign is to be treated as a
                    # preprocessor directive.

                    output_and_expand_line = False

With this change, I'm able to run the preprocessor on Python code without getting spurious errors.  I'd like to suggest that a command-line option be added to pcpp to enable this behavior.  This should be a nearly trivial change, and considerably extends the applicability of pcpp.

**Comment by ned14** [comment]
What is wrong with the intercept at https://ned14.github.io/pcpp/#pcpp.Preprocessor.on_directive_handle?

**Comment by ned14** [comment]
Regarding the specific case of # followed by whitespace followed by a directive, I appreciate that strictly speaking you can't have spaces before C preprocessor directives as according to the standard. However it's a very, very common extension to allow people to indent their preprocessor directives.

What's your use case?

**Comment by ned14** [comment]
You, I am wondering why not hook https://ned14.github.io/pcpp/#pcpp.Preprocessor.on_directive_handle and https://ned14.github.io/pcpp/#pcpp.Preprocessor.on_directive_unknown and return None to cause the comment/preprocessor to be preserved exactly, and executed only if it is recognised.

In other words, isn't this implemented already?

**Comment by Phillip-M-Feldman** [comment]
Niall: `on_directive_handle` almost does the job, but isn't called for `#
error` and thus wouldn't be able to intercept that.

**Comment by Phillip-M-Feldman** [comment]
I still think that adding a command-line flag to enable the snippet of code that I submitted is a reasonable solution, enabling this functionality for those users who need it, with no impact to those users who don't.

**Comment by ned14** [comment]
I'll come back to this issue in May. Sorry for the delay.

**Comment by ned14** [comment]
Ok, I've improved the handling of directives so you can do what you want. Demo can be found at https://github.com/ned14/pcpp/blob/master/tests/issue0027.py

**Comment by Phillip-M-Feldman** [comment]
This is fantastic!  Thanks!
