### ISSUE TITLE
missing folder pcpp/ply/ply

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [ned14/pcpp#28]
When I ran `python setup.py`, I initially got the following error:

P:\Computer\Python\pcpp>python setup.py install
running install
running bdist_egg
running egg_info
writing pcpp.egg-info\PKG-INFO
writing top-level names to pcpp.egg-info\top_level.txt
writing dependency_links to pcpp.egg-info\dependency_links.txt
writing entry points to pcpp.egg-info\entry_points.txt
error: package directory 'pcpp/ply/ply' does not exist

I manually created the missing directory and ran setup.py, and it then appears to have worked.

**Comment by ned14** [comment]
I've tested this, and not found a problem.

Were you using the git repo or something?

**Comment by Phillip-M-Feldman** [comment]
It has been a while, but I believe that I downloaded and expanded a .zip of the repo.
