### ISSUE TITLE
Publish new release for Python 3.8?

### ISSUE THREAD

**Issue by auscompgeek** [ned14/pcpp#31]
pcpp 1.20.1 breaks on Python 3.8 due to the use of `time.clock()`, which I see has been fixed on master.

I would like my CI to pass on Python 3.8. It'd be great if a new release could be published on PyPI.

**Comment by ned14** [comment]
A very reasonable request. I keep hoping to get the time to finish the new expression evaluator, but in reality it's going to be a few months out yet. I'll see what I can do.

**Comment by ned14** [comment]
Done!
