### ISSUE TITLE
Running the preprocessor causes differences in the repository

### ISSUE THREAD

**Issue by Sei-Lisa** [ned14/pcpp#55]
The file pcpp/parsetab.py is re-generated when the preprocessor is run under Python 2. The generated version does not match the version present in the repository, causing differences in `git diff`.

This is being a problem for my project because pcpp is included as a git submodule, and it is marked as dirty.

**Comment by ned14** [comment]
Confirmed. Sorry about that, the ply documentation says that should never occur.

**Comment by ned14** [comment]
Hopefully fixed now. Let me know if it is not fixed. Thanks for the BR!

**Comment by Sei-Lisa** [comment]
Thanks, it appears to work now. I can't help wondering, if the file is re-generated when run, can't it be just removed from the repository, letting the installation generate it?

**Comment by ned14** [comment]
For those who run only from optimised bytecode python, or those using pypy or other such JIT technologies, self generation is not permitted. You can probably guess at what I want to get working next now that we no longer use `eval()`.
