### ISSUE TITLE
Preprocessor to AND, OR options

### ISSUE THREAD

**Issue by munnabhatia** [ned14/pcpp#66]
If a condition as such :

#define CONDITION_1  ON

#if ((CONDITION_1 == ON) || (CONDITION_2 == OFF))
<required code>
#endif

In the example, if CONDITION_1 macro is defined and is ON and CONDITION_2 macro is not defined, in such scenarios the preprocessor doesn't get resolved ie. it still prints as :

#if ((CONDITION_1 == ON) || (CONDITION_2 == OFF))
<required code>
#endif

I expect, condition_2 shouldn't have been checked as per normal C. Is my expectation wrong ? Similarly in usage of AND

**Comment by ned14** [comment]
Can you supply the command line args you fed to pcpp to yield this result please?

**Comment by munnabhatia** [comment]
Was running it on default without any arguments . Just -o.

[Off-topic but I think might resolve the issue] Is there a way to not expand the macros / macro like functions in the generated file ?

**Comment by ned14** [comment]
test.h:
```
#define CONDITION_1 ON

#if ((CONDITION_1 == ON) || (CONDITION_2 == OFF))
Foo
#endif
```
I run:
```
pcpp -o test1.i test.h
```
test1.i:
```
#line 4 "test.h"
Foo
```
I run:
```
gcc -E -o test2.i test.h
```
test2.i:
```
# 1 "test.h"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "test.h"



Foo
```
Looks to me pcpp is doing the right thing here?

**Comment by munnabhatia** [comment]
1. Could you please tell, use of which command line option would have **disabled** such output?
2. Is there a way to disable the expansion of macros and only process the #if(s)?

**Comment by ned14** [comment]
To get exactly what you want, you'll need to customise the preprocessor hooks. See https://ned14.github.io/pcpp/preprocessor.html#pcpp.preprocessor.PreprocessorHooks.

If you want some macros to be expanded but not others, the Readme on the front page tells you how.
