### ISSUE TITLE
add release 1.30 to github

### ISSUE THREAD

**Issue by s9105947** [ned14/pcpp#69]
Dear Maintainer,

in an attempt to upgrade from pcpp 1.21 to 1.30, I noticed that there is no release of that version under the [github releases](https://github.com/ned14/pcpp/releases).
Downstream PyPI however [has it listed as a separate release](https://pypi.org/project/pcpp/#history).

Could you please add a release in github too, so that [other](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/python-modules/pcpp/default.nix) [distributors](https://aur.archlinux.org/packages/python-pcpp/) downstream can grab the latest version from here too?
(Currently they are either outdated or point to the PyPI source.)

On that note: Thanks for your work, the various `--passthru-[...]` options are a real game changer for me using a preprocessor.

**Comment by ned14** [comment]
Sorry that was an oversight. Done! Thanks for reporting the issue.
